[workspace]
resolver = "2"
members = [
    "src/fungible_token_backend",
]

[workspace.dependencies]
candid = "0.10"
ic-cdk = "0.13"
ic-stable-structures = "0.6"
serde = { version = "1.0", features = ["derive"] }
